version: 2

project_name: prism-in-k8s

before:
  hooks:
    - go mod tidy

builds:
  - id: prism-in-k8s
    main: ./main.go
    binary: prism-in-k8s
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

dockers:
  - id: amd64
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/gold-kou/prism-in-k8s:{{ .Version }}-amd64
      - ghcr.io/gold-kou/prism-in-k8s:latest-amd64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.source=https://github.com/gold-kou/prism-in-k8s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - id: arm64
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/gold-kou/prism-in-k8s:{{ .Version }}-arm64
      - ghcr.io/gold-kou/prism-in-k8s:latest-arm64
    dockerfile: Dockerfile.release
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.source=https://github.com/gold-kou/prism-in-k8s
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: ghcr.io/gold-kou/prism-in-k8s:{{ .Version }}
    image_templates:
      - ghcr.io/gold-kou/prism-in-k8s:{{ .Version }}-amd64
      - ghcr.io/gold-kou/prism-in-k8s:{{ .Version }}-arm64
  - name_template: ghcr.io/gold-kou/prism-in-k8s:latest
    image_templates:
      - ghcr.io/gold-kou/prism-in-k8s:latest-amd64
      - ghcr.io/gold-kou/prism-in-k8s:latest-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  draft: false
  prerelease: auto
