kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            cpu-manager-policy: static
            system-reserved: "cpu=500m,memory=1Gi"
            kube-reserved: "cpu=500m,memory=1Gi"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            cpu-manager-policy: static
            system-reserved: "cpu=500m,memory=1Gi"
            kube-reserved: "cpu=500m,memory=1Gi"
