microserviceName: "sample"
microserviceNamespace: "sample"
prismMockSuffix: "-prism-mock"
# istioMode: true
# virtualServiceRoutes:
#   - name: "example1"
#     uriPrefix: "/example1/"
#     method: "GET"
#     delayNanos: 100000000  # 100ms
#     delayPercentage: 100.0
