name: main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

permissions:
  contents: read # for actions/checkout

jobs:
  setup-test-cluster:
    name: Setup Test Cluster
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install istioctl
        run: |
          curl -L https://istio.io/downloadIstio | sh -
          export PATH=$$PWD/istio-*/bin:$$PATH
          istioctl install --set profile=default --timeout=10m -y

      - name: Check out code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: 0.25.0
          config: kube-config.yaml
          cluster_name: prism-test-cluster

      - name: Set kubectl context
        run: kubectl config use-context kind-prism-test-cluster

      - name: Istioctl install on kind cluster
        run: istioctl install --set profile=default -y;
  tests:
    needs:
      - setup-test-cluster
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Run tests
        run: |
          make test